language: cpp


matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - clang-tidy-4.0
          - gcc-6
          - g++-6

    compiler: g++
    script:
      - make even_digits -std=c++11

  - os: osx
    compiler: g++
    script: 

      - rm test_even_digits
      - make test_even_digits -std=c++11
      - ./test_even_digits
      - rm even_digits
      - make even_digits -std=c++11