language: cpp


matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - clang-tidy-4.0
          - gcc-6
          - g++-6

    compiler: g++
    script:
      - make even_digits
      - clang-tidy -checks=-*,clang-analyzer-*,-clang-analyzer-cplusplus* src/even_digits.cpp -- 

  - os: osx
    compiler: g++
    script: 
      - make test
      - rm even_digits
      - make even_digits